version: '3.8'

services:
  nodeserver:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: nodeserver
    ports:
      - 3001:3001
    networks:
      - nodeserver_network
  nginx:
    container_name: nginx
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
  dbmysql:
    container_name: db_mysql
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    tty: true
    volumes:
      - data_mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOR_USER=root
    networks:
      - nodeserver_network
    ports:
      - "3306:3306"

networks:
  nodeserver_network:

volumes:
  data_mysql: