version: '3.8'

services:
  nodeserver:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: nodeserver
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    ports:
      - "3001:3001"
    networks:
      - nodeserver_network
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    container_name: nginx
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - nodeserver_network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOR_USER=root
    networks:
      - nodeserver_network
    ports:
      - "3306:3306"

networks:
  nodeserver_network:

volumes:
  mysql_data: